"""
initial schema

Revision ID: dbbc70bac54f
Revises: 
Create Date: 2026-06-01 18:17:12.617337

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "dbbc70bac54f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("accounts",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("login", sa.String(length=64), nullable=False),
    sa.Column("password_hash", sa.Text(), nullable=False),
    sa.Column("is_active", sa.Boolean(), nullable=False),
    sa.Column("must_change_password", sa.Boolean(), nullable=False),
    sa.Column("totp_secret", sa.String(length=64), nullable=True),
    sa.Column("failed_attempts", sa.Integer(), nullable=False),
    sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_accounts_login"), "accounts", ["login"], unique=True)
    op.create_table("agent_faults",
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column("agent_id", sa.String(length=36), nullable=False),
    sa.Column("component", sa.String(length=64), nullable=False),
    sa.Column("operation", sa.String(length=128), nullable=False),
    sa.Column("exception_type", sa.String(length=255), nullable=False),
    sa.Column("message", sa.Text(), nullable=False),
    sa.Column("traceback", sa.Text(), nullable=False),
    sa.Column("severity", sa.String(length=16), nullable=False),
    sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_agent_faults_agent_id"), "agent_faults", ["agent_id"], unique=False)
    op.create_index("ix_fault_agent_occurred", "agent_faults", ["agent_id", "occurred_at"], unique=False)
    op.create_table("agent_tokens",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("token_hash", sa.String(length=64), nullable=False),
    sa.Column("label", sa.String(length=128), nullable=True),
    sa.Column("agent_id", sa.String(length=36), nullable=True),
    sa.Column("endpoint_url", sa.String(length=256), nullable=True),
    sa.Column("is_active", sa.Boolean(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_agent_tokens_agent_id"), "agent_tokens", ["agent_id"], unique=False)
    op.create_index(op.f("ix_agent_tokens_token_hash"), "agent_tokens", ["token_hash"], unique=True)
    op.create_table("agents",
    sa.Column("agent_id", sa.String(length=36), nullable=False),
    sa.Column("name", sa.String(length=128), nullable=True),
    sa.Column("version", sa.String(length=32), nullable=True),
    sa.Column("status", sa.String(length=16), nullable=False),
    sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
    sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint("agent_id")
    )
    op.create_table("error_groups",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("agent_id", sa.String(length=36), nullable=False),
    sa.Column("fingerprint", sa.String(length=64), nullable=False),
    sa.Column("service", sa.String(length=255), nullable=False),
    sa.Column("environment", sa.String(length=64), nullable=False),
    sa.Column("exception_type", sa.String(length=255), nullable=False),
    sa.Column("title", sa.Text(), nullable=False),
    sa.Column("severity", sa.String(length=16), nullable=False),
    sa.Column("status", sa.String(length=16), nullable=False),
    sa.Column("count", sa.BigInteger(), nullable=False),
    sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
    sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
    sa.Column("last_notified_at", sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("agent_id", "fingerprint", name="uq_group_agent_fingerprint")
    )
    op.create_index(op.f("ix_error_groups_agent_id"), "error_groups", ["agent_id"], unique=False)
    op.create_index(op.f("ix_error_groups_fingerprint"), "error_groups", ["fingerprint"], unique=False)
    op.create_index(op.f("ix_error_groups_service"), "error_groups", ["service"], unique=False)
    op.create_index("ix_group_agent_lastseen", "error_groups", ["agent_id", "last_seen"], unique=False)
    op.create_table("self_errors",
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column("component", sa.String(length=128), nullable=False),
    sa.Column("exception_type", sa.String(length=255), nullable=False),
    sa.Column("message", sa.Text(), nullable=False),
    sa.Column("traceback", sa.Text(), nullable=False),
    sa.Column("fingerprint", sa.String(length=64), nullable=False),
    sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("count", sa.BigInteger(), nullable=False),
    sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index("ix_self_error_occurred", "self_errors", ["occurred_at"], unique=False)
    op.create_index(op.f("ix_self_errors_fingerprint"), "self_errors", ["fingerprint"], unique=False)
    op.create_table("server_metrics",
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column("agent_id", sa.String(length=36), nullable=False),
    sa.Column("cpu_percent", sa.Float(), nullable=False),
    sa.Column("mem_percent", sa.Float(), nullable=False),
    sa.Column("mem_used", sa.BigInteger(), nullable=False),
    sa.Column("mem_total", sa.BigInteger(), nullable=False),
    sa.Column("net_bytes_sent", sa.BigInteger(), nullable=False),
    sa.Column("net_bytes_recv", sa.BigInteger(), nullable=False),
    sa.Column("load_1", sa.Float(), nullable=False),
    sa.Column("load_5", sa.Float(), nullable=False),
    sa.Column("load_15", sa.Float(), nullable=False),
    sa.Column("disk_percent", sa.Float(), nullable=True),
    sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index("ix_metric_agent_captured", "server_metrics", ["agent_id", "captured_at"], unique=False)
    op.create_index(op.f("ix_server_metrics_agent_id"), "server_metrics", ["agent_id"], unique=False)
    op.create_table("account_agents",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("account_id", sa.Uuid(), nullable=False),
    sa.Column("agent_token_id", sa.Uuid(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["agent_token_id"], ["agent_tokens.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("account_id", "agent_token_id", name="uq_account_agent")
    )
    op.create_index(op.f("ix_account_agents_account_id"), "account_agents", ["account_id"], unique=False)
    op.create_index(op.f("ix_account_agents_agent_token_id"), "account_agents", ["agent_token_id"], unique=False)
    op.create_table("bots",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("account_id", sa.Uuid(), nullable=False),
    sa.Column("platform", sa.String(length=32), nullable=False),
    sa.Column("bot_token_encrypted", sa.Text(), nullable=False),
    sa.Column("bot_username", sa.String(length=128), nullable=True),
    sa.Column("invite_key", sa.String(length=64), nullable=False),
    sa.Column("invite_expires_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("chat_id", sa.String(length=64), nullable=True),
    sa.Column("status", sa.String(length=16), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_bots_account_id"), "bots", ["account_id"], unique=False)
    op.create_index(op.f("ix_bots_invite_key"), "bots", ["invite_key"], unique=True)
    op.create_table("error_reports",
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column("group_id", sa.Uuid(), nullable=False),
    sa.Column("agent_id", sa.String(length=36), nullable=False),
    sa.Column("service", sa.String(length=255), nullable=False),
    sa.Column("environment", sa.String(length=64), nullable=False),
    sa.Column("severity", sa.String(length=16), nullable=False),
    sa.Column("exception_type", sa.String(length=255), nullable=False),
    sa.Column("message", sa.Text(), nullable=False),
    sa.Column("traceback", sa.Text(), nullable=False),
    sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(["group_id"], ["error_groups.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_error_reports_agent_id"), "error_reports", ["agent_id"], unique=False)
    op.create_index(op.f("ix_error_reports_group_id"), "error_reports", ["group_id"], unique=False)
    op.create_index("ix_report_group_occurred", "error_reports", ["group_id", "occurred_at"], unique=False)
    op.create_table("notifications",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("account_id", sa.Uuid(), nullable=False),
    sa.Column("kind", sa.String(length=32), nullable=False),
    sa.Column("severity", sa.String(length=16), nullable=False),
    sa.Column("title", sa.Text(), nullable=False),
    sa.Column("body", sa.Text(), nullable=False),
    sa.Column("ref", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index("ix_notification_account_created", "notifications", ["account_id", "created_at"], unique=False)
    op.create_index(op.f("ix_notifications_account_id"), "notifications", ["account_id"], unique=False)
    op.create_table("projects",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("account_id", sa.Uuid(), nullable=False),
    sa.Column("name", sa.String(length=128), nullable=False),
    sa.Column("slug", sa.String(length=128), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("account_id", "slug", name="uq_project_account_slug")
    )
    op.create_index(op.f("ix_projects_account_id"), "projects", ["account_id"], unique=False)
    op.create_index(op.f("ix_projects_slug"), "projects", ["slug"], unique=False)
    op.create_table("sessions",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("account_id", sa.Uuid(), nullable=False),
    sa.Column("token_hash", sa.String(length=64), nullable=False),
    sa.Column("remember", sa.Boolean(), nullable=False),
    sa.Column("ip", sa.String(length=64), nullable=True),
    sa.Column("user_agent", sa.String(length=256), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_sessions_account_id"), "sessions", ["account_id"], unique=False)
    op.create_index(op.f("ix_sessions_token_hash"), "sessions", ["token_hash"], unique=True)
    op.create_table("container_assignments",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("project_id", sa.Uuid(), nullable=False),
    sa.Column("agent_id", sa.String(length=36), nullable=False),
    sa.Column("container_key", sa.String(length=255), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("project_id", "agent_id", "container_key", name="uq_assignment")
    )
    op.create_index(op.f("ix_container_assignments_agent_id"), "container_assignments", ["agent_id"], unique=False)
    op.create_index(op.f("ix_container_assignments_project_id"), "container_assignments", ["project_id"], unique=False)
    op.create_table("container_states",
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column("agent_id", sa.String(length=36), nullable=False),
    sa.Column("container_id", sa.String(length=64), nullable=False),
    sa.Column("name", sa.String(length=255), nullable=False),
    sa.Column("image", sa.String(length=255), nullable=False),
    sa.Column("status", sa.String(length=64), nullable=False),
    sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("restarts", sa.Integer(), nullable=False),
    sa.Column("cpu_percent", sa.Float(), nullable=True),
    sa.Column("mem_percent", sa.Float(), nullable=True),
    sa.Column("mem_usage", sa.BigInteger(), nullable=True),
    sa.Column("net_rx", sa.BigInteger(), nullable=True),
    sa.Column("net_tx", sa.BigInteger(), nullable=True),
    sa.Column("blk_read", sa.BigInteger(), nullable=True),
    sa.Column("blk_write", sa.BigInteger(), nullable=True),
    sa.Column("labels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("project_id", sa.Uuid(), nullable=True),
    sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("agent_id", "container_id", name="uq_container_agent_id")
    )
    op.create_index("ix_container_agent", "container_states", ["agent_id"], unique=False)
    op.create_index(op.f("ix_container_states_agent_id"), "container_states", ["agent_id"], unique=False)
    op.create_index(op.f("ix_container_states_project_id"), "container_states", ["project_id"], unique=False)
    op.create_table("project_rules",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("project_id", sa.Uuid(), nullable=False),
    sa.Column("match_type", sa.String(length=32), nullable=False),
    sa.Column("match_value", sa.String(length=255), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_project_rules_project_id"), "project_rules", ["project_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_project_rules_project_id"), table_name="project_rules")
    op.drop_table("project_rules")
    op.drop_index(op.f("ix_container_states_project_id"), table_name="container_states")
    op.drop_index(op.f("ix_container_states_agent_id"), table_name="container_states")
    op.drop_index("ix_container_agent", table_name="container_states")
    op.drop_table("container_states")
    op.drop_index(op.f("ix_container_assignments_project_id"), table_name="container_assignments")
    op.drop_index(op.f("ix_container_assignments_agent_id"), table_name="container_assignments")
    op.drop_table("container_assignments")
    op.drop_index(op.f("ix_sessions_token_hash"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_account_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_projects_slug"), table_name="projects")
    op.drop_index(op.f("ix_projects_account_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_notifications_account_id"), table_name="notifications")
    op.drop_index("ix_notification_account_created", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index("ix_report_group_occurred", table_name="error_reports")
    op.drop_index(op.f("ix_error_reports_group_id"), table_name="error_reports")
    op.drop_index(op.f("ix_error_reports_agent_id"), table_name="error_reports")
    op.drop_table("error_reports")
    op.drop_index(op.f("ix_bots_invite_key"), table_name="bots")
    op.drop_index(op.f("ix_bots_account_id"), table_name="bots")
    op.drop_table("bots")
    op.drop_index(op.f("ix_account_agents_agent_token_id"), table_name="account_agents")
    op.drop_index(op.f("ix_account_agents_account_id"), table_name="account_agents")
    op.drop_table("account_agents")
    op.drop_index(op.f("ix_server_metrics_agent_id"), table_name="server_metrics")
    op.drop_index("ix_metric_agent_captured", table_name="server_metrics")
    op.drop_table("server_metrics")
    op.drop_index(op.f("ix_self_errors_fingerprint"), table_name="self_errors")
    op.drop_index("ix_self_error_occurred", table_name="self_errors")
    op.drop_table("self_errors")
    op.drop_index("ix_group_agent_lastseen", table_name="error_groups")
    op.drop_index(op.f("ix_error_groups_service"), table_name="error_groups")
    op.drop_index(op.f("ix_error_groups_fingerprint"), table_name="error_groups")
    op.drop_index(op.f("ix_error_groups_agent_id"), table_name="error_groups")
    op.drop_table("error_groups")
    op.drop_table("agents")
    op.drop_index(op.f("ix_agent_tokens_token_hash"), table_name="agent_tokens")
    op.drop_index(op.f("ix_agent_tokens_agent_id"), table_name="agent_tokens")
    op.drop_table("agent_tokens")
    op.drop_index("ix_fault_agent_occurred", table_name="agent_faults")
    op.drop_index(op.f("ix_agent_faults_agent_id"), table_name="agent_faults")
    op.drop_table("agent_faults")
    op.drop_index(op.f("ix_accounts_login"), table_name="accounts")
    op.drop_table("accounts")
    # ### end Alembic commands ###
